import Lexend from "next/font/local";
import "./globals.css";
import  "bootstrap/dist/css/bootstrap.min.css"
import Leftnav from './dashboard/leftnav/page';
const lexend_init = Lexend({
  src: "./fonts/Lexend-Light.ttf",
  variable: "--font-lexend-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend_init.variable}`}>
        <main className="lexend_font container-fluid">
          <div className="row">
              <Leftnav/>
              {children}
          </div>
        </main>
      </body>
    </html>
  );
}
